### ISSUE TITLE
How accurate is the result of decompiling .bf files?

### ISSUE THREAD

**Issue by IronicallySerious** [TGEnigma/Atlus-Script-Tools#17]
I am just checking out the .bf files in P4G for PC to know what kind of code went into making P4G. How accurate would you say is the decompiled code to the way Atlus' implemented the flow scripts?

Did they have these long hardcoded values sent into functions and super long series of if/else statements like from `commu00.bf`:

```
void commu_yoru()
{
    int localVariable0 = FUNCTION_0033();
    int localVariable1 = FUNCTION_0034();
    int localVariable3 = FUNCTION_0036();
    
    if ( localVariable0 == 4 && localVariable1 == 11 )
    {
        eve_0411_midnight();
        return;
    }
    else if ( localVariable0 == 4 && localVariable1 == 13 )
    {
        eve_0413_midnight();
        FUNCTION_003C();
        return;
    }
    .
    .
    . // There is a long series of if/else series 
```

Is this accurate? I was trying to see if I could learn anything from their code but it all looks quite unreadable to me. 

If this is like a C program decompilation result (which is super optimized and has no debug symbols etc.) then this kind of output is kinda expected to me. Just wanted to know if do you think these scripts were implemented like this...

**Comment by ShrineFox** [comment]
Unfortunately a lot has been lost in the translation to the binary format (variable names, function names...) so you're right, the result is akin to a C program decompilation. The if/else chains were probably originally switch statements, but other than stuff like that it should be *mostly* accurate. Sometimes the decompiler fails to declare variables before using them, or interprets float values incorrectly. In those cases some manual editing is necessary to recompile. But other than that I'd say it's as close as we'll get to the original script. There was a game that left the uncompiled source of some of the BF scripts in it, but at the moment I don't remember which one

**Comment by IronicallySerious** [comment]
Thanks, I guess that answers the question. Really wanted to see their code though but oh well :p
