### ISSUE TITLE
text containing slash characters '/' can no longer be recompiled

### ISSUE THREAD

**Issue by DeathChaos25** [TGEnigma/Atlus-Script-Tools#33]
As of recent versions, any regular text files containing any slash characters can no longer be recompiled into bmd/bf files as the compiler will spit out multiple errors every time it reads one.

Here are some sample bmd files from Perona 5 where this issue occurs;
[datMsg.zip](https://github.com/TGEnigma/Atlus-Script-Tools/files/7067979/datMsg.zip)

**Comment by TGEnigma** [comment]
fixes as of commit 1622cad4d2404da0ec9c058e31b8c59e1ede06a6
